on:
  workflow_dispatch: 
    inputs:
      releaseName:
        description: "Release Name"
        required: true
        type: string
      version:
        description: "Release version (e.g., 1.1.0)"
        required: true
        type: string

name: Build Release

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: git ls-files | zip LME-${{ inputs.version }}.zip -@

      - name: Get current date 
        id: date
        run: echo "{date}={$(date + '%Y-%m-%d')}" >> $GITHUB_STATE

      - name: Release 
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.releaseName }}
          tag_name: v${{ inputs.version }}
          files: LME-${{ steps.tag.outputs.tag }}.zip
          draft: true
          generate_release_notes: true 
          body: "## [${{ steps.tag.outputs.tag }}] - Timberrrrr! - ${{ env.date }}"
          fail_on_unmatched_files: true


